### PR TITLE
Updated responses to match Wagtail 4 chooser names

### LINKED ISSUE #33: Image and document choosers don't update content
On Wagtail 4.0.x, the image and document choosers from this package appear to work - popups and navigation are all fine. But when you have chosen the document (or image) and the modal closes, the new content is not incorporated into the text in the editor. There are no errors in the JS console or server logs.

### PR DESCRIPTION
**Pull request by cnk**
Fixes #33 

However, changing these 2 lines means at this point, the code is no longer agnostic between Wagtail 3 and 4. @lb- I don't know a trick like the try/catch for python imports that would allow this to work on both sets. Should we create a pypi release with the previous code (and stating Wagtail <= 3) and then merge this and declare this Wagtail 4+? If so, should we go ahead and remove the ifs in the imports? 

(I have tested this fix and it works on Wagtail 4.0 and 4.1)

### CODE REVIEW

**Comment by lb-** [comment]
Hey @cnk  - it probably makes sense to try to do a 3.0 compatible release and then do this change as a different one that is 4.0 compatible but drops < 3.0.

**Comment by lb-** [comment]
https://github.com/wagtail-nest/wagtail-hallo/blob/main/wagtail_hallo/test/tests/hallo.test.js

Wagtail uses Jest - but here are the docs https://jestjs.io/

```
npm ci
npm run test # run all tests
```

```
npm run test -- --watch
```

https://jestjs.io/docs/cli - to pass in cli arguments to npm scripts remember to use the `--` before these

**Comment by nickmoreton** [comment]
@cnk FYI I just submitted https://github.com/wagtail-nest/wagtail-hallo/pull/38 for the wagtail 4.2 upgrade. It might mean that this change isn't required. 🤞

**Comment by zerolab** [comment]
This change is very much required in that it related to the JS callbacks for the choosers

**Comment by cnk** [comment]
Fixed in #43 - including dropping support for Wagtail < 4.0

**Pull request closed without merging**
