### PR TITLE
Add support for Wagtail 4

### PR DESCRIPTION
**Pull request by katdom13**
Release notes: https://docs.wagtail.org/en/stable/releases/4.0.html

- Fixed imports and panels
- Updated test matrix to include wagtail 4
- Update version and documentation

```
Found 21 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.....s.s.s...........
----------------------------------------------------------------------
Ran 21 tests in 0.192s

OK (skipped=3)
```

### CODE REVIEW

**Comment by lb-** [comment]
This might replace https://github.com/wagtail-nest/wagtail-hallo/pull/29

I have triggered the runners

**Comment by katdom13** [comment]
Some tests have failed. I have edited some files, please trigger the runnners. Thank you!

**Comment by lb-** [comment]
Done.

**Comment by lb-** [comment]
@cnk any chance you could do a quick review of this and see if this works for one of your projects?

Code changes look solid to me but have not had the chance to run against bakerydemo / local project yet.

Thanks so much @katdom13 !

**Comment by cnk** [comment]
I need to double check I have integrated the changes correctly but it looks to me like image insertion and document links do not work.

**Comment by cnk** [comment]
Excellent work. This version of the code will run on both Wagtail 3 and 4. 

However, on Wagtail 4, image insertion and links created by the document chooser do not currently work but I am going to merge this and deal with those issues separately.

**Pull request merged**
